version: '3.8'

services:
  bot:
    build: .
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      - ollama
    networks:
      - bot-network
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - bot-network
    restart: unless-stopped

networks:
  bot-network:
    driver: bridge

volumes:
  ollama_data: